# Streamlit Secrets - NE PAS COMMITTER CE FICHIER (ajoutez .streamlit/secrets.toml dans votre .gitignore)
# Modifiez la valeur ci-dessous pour définir votre mot de passe administrateur.

admin_password = "220805"
